### ISSUE TITLE
Refactor oci client

### ISSUE THREAD

**Issue by souleb** [fluxcd/pkg#741]
The client in `pkg/oci` can be refactored to include some optimization:
- use `remote` instead of `crane` like in https://github.com/fluxcd/source-controller/pull/1244
- provide a client that can be used in both `source-controller` and `flux2`.
- optimize for large files download/uploads

## Tasks:
- [ ] optimize for large files download using `http key range` where possible #738 
- [ ] switch from `crane` to `remote`
- [ ] enable OCI client in SC

**Comment by matheuscscp** [comment]
Hi @hawkaii, thanks for volunteering! If you'd like to contribute towards improvements related to `pkg/oci` I'd suggest analyzing what was done in the pull request linked above, figuring out why is it important, and if we really need to do it in `pkg/oci` as well before using it in source-controller or not. If you're interested I'll let you work on this, and feel free to reach out for help if you need 🤗

**Comment by Iam-Karan-Suresh** [comment]
Hi @matheuscscp I would like to work on this issue. If it is looks good to you happy to start work 🙏.
